ignoreGeneratedHeader = false
severity = "warning"
confidence = 0.8
errorCode = 1
warningCode = 1
enableAllRules = true

[rule.add-constant]
  Disabled = true
[rule.file-header]
  Disabled = true
[rule.max-public-structs]
  Disabled = true
[rule.function-length]
  Disabled = true
[rule.deep-exit]
  Disabled = true
[rule.cyclomatic]
  Disabled = true
[rule.cognitive-complexity]
  Disabled = true
[rule.flag-parameter]
  Disabled = true
[rule.banned-characters]
  Disabled = true

[rule.line-length-limit]
  Disabled = true
[rule.unhandled-error]
  arguments = ["fmt.Printf", "fmt.Println"]
[rule.argument-limit]
  arguments = [6]
[rule.function-result-limit]
  arguments = [3]
